typer_assistant:
    assistant_name: Selena
    human_companion_name: Andrew
    ears: realtime-stt
    brain: "ollama:phi4:latest" # only deepseek-v3
    voice: elevenlabs # local, elevenlabs
    elevenlabs_voice: Mr9wQdBrsBklZj5Rneuu # Dan's Voice WejK3H1m7MI9CHnIjW9K
base_assistant:
    assistant_name: Selena
    human_companion_name: Andrew
    ears: realtime-stt
    brain: "ollama:phi4" # deepseek-v3, ollama:phi4, ollama:<any installed model>
    voice: local # local, elevenlabs
    elevenlabs_voice: Mr9wQdBrsBklZj5Rneuu # Dan's Voice WejK3H1m7MI9CHnIjW9K
